# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZSearch
    pod 'Hero'
    pod 'SnapKit', '~> 5.0.0'

end
